# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anuncio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localidade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuncio.Localidade')),
            ],
        ),
        migrations.AddField(
            model_name='anuncio',
            name='ap_pendente',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='localidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuncio.Localidade'),
        ),
    ]
